### ISSUE TITLE
The last SubTable on the page not appear

### ISSUE THREAD

**Issue by bebone** [chafiq/TableBundle#16]
Hello,
I have made a Subtable but the last sub on anypage of the Table not appear  (in your example too)

Have you got a solution to fix that? Many thanks

**Comment by chafiq** [comment]
Hi,

Thank you for reporting this bug. I will fixe it this week-end

Chafiq

Envoyé de mon iPhone

**Comment by bebone** [comment]
Ok, Merci ! Thank you !

**Comment by chafiq** [comment]
Fixed
