### ISSUE TITLE
Need "search" instead of "rechercher"

### ISSUE THREAD

**Issue by ghost** [chafiq/TableBundle#2]
When I enabled filtering on a column and the filter text box is displayed, the placeholder is in French. Can we have the default be in English and add the French to the translation?

![screen shot 2015-10-13 at 1 12 55 pm](https://cloud.githubusercontent.com/assets/6107646/10466972/28248c7c-71ac-11e5-9179-0e064ab5ba31.png)

**Comment by ghost** [comment]
I have submitted a PR: https://github.com/chafiq/TableBundle/pull/3

**Comment by chafiq** [comment]
Great, but for translation you have to replace the static text "Search" with {{ 'Search'|trans({}, 'EMCTableBundle') }}. After that, I'll merge the pull request. :)

**Comment by ghost** [comment]
@chafiq I believe that change is already in the PR?

**Comment by chafiq** [comment]
@alanscott sorry, didn't see that. I merge the PR right now
