### ISSUE TITLE
Export menu clipped off window

### ISSUE THREAD

**Issue by ghost** [chafiq/TableBundle#4]
The drop down menu from the Export link is left-justified and being clipped off the screen if the table is drawn to "edge" of the screen. In the attached screenshot, I use Bootstrap3 "container-fluid" to house the table. As you can see, the menu is clipped off by the window of the browser. Since the button is right-aligned on the table, maybe we can right-align the drop down menu to prevent it from being clipped off.

![screen shot 2015-10-13 at 1 27 46 pm](https://cloud.githubusercontent.com/assets/6107646/10467435/883594ce-71ae-11e5-8bd0-162b467c4079.png)

**Comment by ghost** [comment]
I have added a PR: https://github.com/chafiq/TableBundle/pull/5

**Comment by chafiq** [comment]
I've merge the PR
