### ISSUE TITLE
"icon" parameter in Anchor column is not utilized

### ISSUE THREAD

**Issue by ghost** [chafiq/TableBundle#6]
The Anchor block in the extensions.html.twig does nothing with the `icon` parameter passed in the column definition.

**Comment by chafiq** [comment]
Very interesting @alanscott,
Assuming that icons, texts and images are anchorable. I think that the best conception is that IconType, TextType, ImageType extends AnchorType. So, it will be available in the next release 1.2.0.

**Comment by ghost** [comment]
@chafiq Definitely a better solution! Thanks.

**Comment by chafiq** [comment]
Version 1.2.0. Be care about changes
