### ISSUE TITLE
Error: Call to a member function format() on null

### ISSUE THREAD

**Issue by ghost** [chafiq/TableBundle#8]
DateTime column type requires the value to not be null in order to apply the formatter. Perhaps we can add a check to only apply the formatter if the value is not null?

**Comment by chafiq** [comment]
It will be also fixed in the new version 1.2.0
DatetimeType will will use IntlDateFormatter for Internationalization
Note : date_format has changed : available values are NONE, FULL, LONG, MEDIUM, SHORT
          time_format (new options) : available values are NONE, FULL, LONG, MEDIUM, SHORT
          format will replace date_format and has priority that intl with (date_format,  time_format)
          locale : locale language if you want to force it, default user language \Locale::getDefault()

**Comment by chafiq** [comment]
Resolved check version 1.2.0
